DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'po_status') THEN
    CREATE TYPE po_status AS ENUM ('PR_PENDING', 'APPROVED', 'WAITING_RECEIVED', 'PARTIAL_RECEIVED', 'CLOSED', 'REJECTED');
  END IF;
END $$;