CREATE OR REPLACE FUNCTION public.create_schedule_on_sr_approval()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
    new_delivery_order_id UUID;
BEGIN
  -- Check if the status has just changed to 'approved' and a do_number has been generated
  IF NEW.status = 'approved' AND OLD.status IS DISTINCT FROM 'approved' AND NEW.do_number IS NOT NULL THEN

    -- 1. Insert into delivery_orders table
    INSERT INTO public.delivery_orders (
      request_id,
      user_id,
      do_number,
      delivery_date,
      delivery_time,
      status,
      notes
      -- items_json can be null initially or populated later
    ) VALUES (
      NEW.id, -- scheduling_request_id
      NEW.user_id,
      NEW.do_number,
      NEW.requested_date,
      NEW.requested_time,
      'in_progress', -- Set DO status to 'in_progress' as requested
      NEW.notes
    )
    RETURNING id INTO new_delivery_order_id;

    -- 2. Update scheduling_requests with the new delivery_order_id
    UPDATE public.scheduling_requests
    SET delivery_order_id = new_delivery_order_id
    WHERE id = NEW.id;

    -- 3. Insert into schedules table (existing logic)
    INSERT INTO public.schedules (
      user_id,
      schedule_date,
      schedule_time,
      type,
      customer_name,
      address,
      technician_name,
      status, -- This is for the schedule, not the DO
      notes,
      phone_number,
      product_category,
      scheduling_request_id,
      do_number,
      customer_id
    ) VALUES (
      NEW.user_id,
      NEW.requested_date,
      NEW.requested_time,
      NEW.type,
      NEW.customer_name,
      NEW.full_address,
      NEW.technician_name,
      'scheduled', -- Initial status for the schedule
      NEW.notes,
      NEW.phone_number,
      NEW.product_category,
      NEW.id, -- Link to the scheduling_request
      NEW.do_number, -- Use the DO number generated by process_scheduling_request_flow
      NEW.customer_id
    )
    ON CONFLICT (scheduling_request_id) DO NOTHING; -- Prevent duplicate schedules if trigger fires multiple times

  END IF;
  RETURN NEW;
END;
$function$;