CREATE OR REPLACE FUNCTION public.create_schedule_on_sr_approval()
RETURNS TRIGGER
LANGUAGE PLPGSQL
SECURITY DEFINER SET search_path = 'public'
AS $$
BEGIN
  -- Check if the status has just changed to 'approved' and a do_number has been generated
  IF NEW.status = 'approved' AND OLD.status IS DISTINCT FROM 'approved' AND NEW.do_number IS NOT NULL THEN
    -- Insert into schedules table
    INSERT INTO public.schedules (
      user_id,
      schedule_date,
      schedule_time,
      type,
      customer_name,
      address,
      technician_name,
      status,
      notes,
      phone_number,
      product_category,
      scheduling_request_id,
      do_number,
      customer_id
    ) VALUES (
      NEW.user_id,
      NEW.requested_date,
      NEW.requested_time,
      NEW.type,
      NEW.customer_name,
      NEW.full_address,
      NEW.technician_name, -- Use the technician name from scheduling_requests
      'scheduled', -- Initial status for the schedule
      NEW.notes,
      NEW.phone_number,
      NEW.product_category,
      NEW.id, -- Link to the scheduling_request
      NEW.do_number, -- Use the DO number generated by process_scheduling_request_flow
      NEW.customer_id
    )
    ON CONFLICT (scheduling_request_id) DO NOTHING; -- Prevent duplicate schedules if trigger fires multiple times

  END IF;
  RETURN NEW;
END;
$$;